#Quiz
names(wcgs2)
attach(wcgs2)
table(chd69, behpat)
prop.table(table(chd69, behpat),2)

aggregate(chol,by = list(chd69), mean, na.rm = T)
aggregate(chol,by = list(chd69), sd, na.rm = T)

aggregate(chol,by = list(chd69, smoke), mean, na.rm = T)
aggregate(chol,by = list(chd69, smoke), sd, na.rm = T)
aggregate(chd69, by = list(chol), mean)
aggregate(sbp, by = list(obesity, race), summary)
aggregate(chd, by = list(obesity, race), table)
mean(chd69, groups = chol)
mean(table(chd69, chol))
mean(chol, groups = chd69)
table(chd69)
table(chd69, smoke)
boxplot(bmi ~ chd69, col = rainbow(4), main = "SBP by BMI Category")
boxplot(sbp ~ behpat, col = rainbow(4), main = "SBP by BMI Category")
boxplot(sbp ~ smoke)

count(chd69)
table(chd69)
table(smoke)
table(smoke, chd69)
table(smoke~chd69)
count(smoke, group_by(chd69))
aggregate(chd69, by = list(smoke), table)
